config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resources :books do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
    
  end

  def new
    @book = Book.new

    render:_form
  end

  def create
    @book = Book.new(book_params)
    
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
    render :_form
  end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :pages)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_book
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = @book.reviews
  end

  def show
  end

  def new
    @review = @book.reviews.new
  end

  def create
    @review = @book.reviews.new(review_params) 

    if @review.save
      redirect_to [@book, @review]
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to [@book, @review]
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to book_reviews_path
  end

  private
    def set_book
      @book = Book.find(params[:books_id])
    end

    def set_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:user, :title, :body )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<h1><%= @book.id ? "Edit #{@book.title}" : "Add New Book"  %>
<hr />
<%= form_with(model: @book, local: true) do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title, required: true, placeholder: "Title: " %>
    <br />
    <br />
    <%= f.label :author %>
    <%= f.text_field :author, required: true, placeholder: "Author: " %>
    <br />
    <br />
    <%= f.label :pages %>
    <%= f.text_field :pages, required: true, placeholder: "Pages: " %>
    <br />
    <br />
  </div>
  <%= f.submit %>
<% end %>
<br />
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
<h1>DPL Library</h1>
<hr />
<%= link_to "Add New Book", new_book_path %>
<% @books.each do |book| %>
  <h2>Title: <%= book.title %></h2>
  <h3>Author: <%= book.author %></h3>
  <h3>Pages: <%= book.pages %></h3>
  <%= link_to "View Book", book_path(book) %>
<% end %>
<br />

app/views/books/new.html.erb
<h1>New Book</h1>

app/views/books/show.html.erb
<h1>Title: <%= @book.title %></h1>
<h2>Author: <%= @book.author %></h2>
<h2>Pages: <%= @book.pages %></h2>

<%= link_to "Edit Book", edit_book_path %>
<%= link_to "Delete Book", book_path(@book), method: :delete %>
<br />
<%= link_to "Back", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyLibrary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>